name = "xxrenq-access-api"
main = "src/index.js"
compatibility_date = "2026-10-02"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "https://xxrenq.github.io"
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "xxrenq-access"
database_id = "1bd6274f-aa68-4bbf-ad0f-e60a3d1ad166"
migrations_dir = "migrations"

[triggers]
crons = ["17 * * * *"]